# https://support.google.com/accounts/answer/6010255
# Permitir que aplicaciones menos seguras utilicen las cuentas
# Let less secure apps access your account
# https://myaccount.google.com/lesssecureapps
swiftmailer:
    #
    #transport: 'gmail'
    #host: '%env(MAILER_HOST)%'
    #username: '%env(MAILER_USER)%'
    #password: '%env(MAILER_PASSWORD)%'
    #
    url: '%env(MAILER_URL)%'
    # Spool Using Memory    
    spool: { type: 'memory' }
    encryption:	ssl
    auth_mode:	login
    host:	smtp.gmail.com      
    stream_options:
        ssl:
            verify_peer: false
            verify_peer_name: false
    ###########################################
    # Disabling Sending (option to development)
    disable_delivery: true
    delivery_addresses: ['seo@prodigia.com']
    ###########################################
    # Source: https://symfony.com/doc/current/email/dev_environment.html#viewing-from-the-web-debug-toolbar
    # To Viewing from the Web Debug Toolbar
    # Using `dev` enviroment in the configuration of web_profiler.yaml select
    #   intercept_redirects: true
    ###########################################

    
