App\Entity\Emails:
    type: entity
    table: emails
    indexes:
        IDX_4C81E852A76ED395:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        note:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        createdOn:
            type: datetime
            nullable: false
            #options:
            #    default: CURRENT_TIMESTAMP
            column: created_on
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: emails
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
