App\Entity\ListRoles:
    type: entity
    table: list_roles
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        role:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        createdOn:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_on
    lifecycleCallbacks: {  }
