App\Entity\ListTypeProject:
    type: entity
    table: list_type_project
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        image:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        basePrice:
            type: float
            nullable: false               
        createdOn:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_on
    oneToMany:
        tasks:
            targetEntity: ListTypeTask
            mappedBy: typeProject
    lifecycleCallbacks: {  }
